# Generated by Django 5.1.1 on 2024-09-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
