# Generated by Django 5.1.1 on 2024-09-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, blank=True)),
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=20)),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
